# Generated by Django 4.1.3 on 2022-11-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_title", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "project",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.IntegerField(default=1)),
                ("text", models.CharField(max_length=255)),
                ("speed", models.IntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audio.project",
                    ),
                ),
            ],
            options={
                "db_table": "audio",
                "abstract": False,
                "managed": True,
            },
        ),
    ]
