# Generated by Django 4.1.3 on 2022-11-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="path",
            field=models.CharField(default="", max_length=255),
        ),
    ]
