# Generated by Django 4.1.3 on 2022-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_audio_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="is_audio_required",
            field=models.BooleanField(default=True),
        ),
    ]
