# Generated by Django 4.1.3 on 2022-11-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email_alter_user_name_alter_user_password"),
        ("audio", "0003_audio_is_audio_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.user",
            ),
            preserve_default=False,
        ),
    ]
