databases:
  host: "host url"
  port: 3306
  database: "db name"
  username: "username"
  password: "passwd"
  timezone: "+09:00"

secrets:
  django: "django-insecure-something"

scheduler:
  interval_sec: 2
  batch_size: 10

token:
  scret: "JWT secret key"
  expire_sec: 3600
